### ISSUE TITLE
wizard gives bad value for `public`

### ISSUE THREAD

**Issue by maxheld83** [DeterminateSystems/flakehub-push#186]
(This might be the wrong place, but I don't know where the push-to-flakehub action wizard is developed)

The [wizard](https://flakehub.com/new) creates something like this:

```yaml
name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "dataheld/NixPlate"
          rolling: true
          visibility: "Public"
          include-output-paths: true

```

but that fails with:

```sh
/home/runner/work/_temp/flakehub-push-fa6bd4ee-f8f6-433d-9b32-6e75f61cd5dd
error: invalid value 'Public' for '--visibility <VISIBILITY>'
  [possible values: public, hidden, unlisted, private]

  tip: a similar value exists: 'public'
```

Changing it to lowercase fixes the problem.
