### ISSUE TITLE
flakehub_push crashes with rolling-prefix set to 1

### ISSUE THREAD

**Issue by flexiondotorg** [DeterminateSystems/flakehub-push#32]
With `rolling-prefix` set to `1` flakehub_push crashes:

Here is an example .yaml: 

```yaml
name: Push to FlakeHub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/flakehub-push@main
        with:
          upload-name: DeterminateSystems/antsy-alien-attack-pico
          visibility: hidden
          rolling-prefix: "1"
```

Here is the relevant error from the logs:

```
Set FLAKEHUB_PUSH_URL=https://install.determinate.systems/flakehub-push/branch/main/X64-Linux?ci=github
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

 37 6145k   37 2310k    0     0  2079k      0  0:00:02  0:00:01  0:00:01 2079k
100 6145k  100 6145k    0     0  5177k      0  0:00:01  0:00:01 --:--:-- 49.2M
2023-08-07T13:58:56.081002Z  INFO flakehub_push:push_new_release{repository=DeterminateSystems/antsy-alien-attack-pico mirror=false upload_name=DeterminateSystems/antsy-alien-attack-pico}: flakehub_push::cli: Preparing release of DeterminateSystems/antsy-alien-attack-pico/1
Error: 
   0: Status 400 Bad Request from metadata POST
      Invalid URL: unexpected character '+' after minor version number

Location:
   src/cli/mod.rs:436

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: flakehub_push::cli::push_new_release with repository=DeterminateSystems/antsy-alien-attack-pico mirror=false upload_name=DeterminateSystems/antsy-alien-attack-pico source=/nix/store/68ng1hgm0cj2mvnpgzl6cbsdajpigzjw-source
      at src/cli/mod.rs:267
   1: flakehub_push::cli::flakehub_push
      at src/cli/mod.rs:120

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Consider reporting this error using this URL: /issues/new
Error: Process completed with exit code 1.
```

The run for the action is here: https://github.com/DeterminateSystems/antsy-alien-attack-pico/actions/runs/5786050519/job/15679975615
