### ISSUE TITLE
flakehub_push crashed when the visibility is `hidden`

### ISSUE THREAD

**Issue by flexiondotorg** [DeterminateSystems/flakehub-push#36]
With `visibility` set to `hidden` (following the change to `unlisted`) flakehub_push crashes when the action runs.

Here's an example action:

```yaml
name: Push to FlakeHub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/flakehub-push@main
        with:
          upload-name: DeterminateSystems/obs-cli-linux
          visibility: hidden
```

Here is the log:

```
Set FLAKEHUB_PUSH_URL=https://install.determinate.systems/flakehub-push/branch/main/X64-Linux?ci=github
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0 6249k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 6249k  100 6249k    0     0  7078k      0 --:--:-- --:--:-- --:--:-- 18.4M
2023-08-09T12:31:34.390798Z  INFO flakehub_push:push_new_release{repository=DeterminateSystems/antsy-alien-attack-pico mirror=false upload_name=DeterminateSystems/antsy-alien-attack-pico}: flakehub_push::cli: Preparing release of DeterminateSystems/antsy-alien-attack-pico/1.0
Error: 
   0: Status 422 Unprocessable Entity from metadata POST
      {"message":"Failed to deserialize the JSON body into the target type","origin":"with_rejection"}

Location:
   src/cli/mod.rs:457

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: flakehub_push::cli::push_new_release with repository=DeterminateSystems/antsy-alien-attack-pico mirror=false upload_name=DeterminateSystems/antsy-alien-attack-pico source=/nix/store/j9zbskdv0prnjng4ikm4dnazxbsr19ay-source
      at src/cli/mod.rs:278
   1: flakehub_push::cli::flakehub_push
      at src/cli/mod.rs:120

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Consider reporting this error using this URL: /issues/new
Error: Process completed with exit code 1.
```

- Example action log: https://github.com/DeterminateSystems/antsy-alien-attack-pico/actions/runs/5809041675/job/15747059324

## Expectation

It would be better if this condition is caught and useful information is output to guide the user to the appropriate corrective action.
