### ISSUE TITLE
flakehub_push crashes if rolling-prefix is major.minor.patch

### ISSUE THREAD

**Issue by flexiondotorg** [DeterminateSystems/flakehub-push#46]
With `rolling-prefix` set to `2.2.3`, flakehub_push crashes when the action runs.

Here's an example action:

```yaml
name: Push to FlakeHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/flakehub-push@main
        with:
          upload-name: DeterminateSystems/obs-cli-linux
          visibility: unlisted
          rolling-prefix: 2.2.3
```

Here's the log:

```
Set FLAKEHUB_PUSH_URL=https://install.determinate.systems/flakehub-push/branch/main/X64-Linux?ci=github
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 6341k  100 6341k    0     0   9.8M      0 --:--:-- --:--:-- --:--:-- 22.6M
2023-08-15T11:46:28.320101Z  INFO flakehub_push:push_new_release{repository=DeterminateSystems/obs-cli-linux mirror=false upload_name=DeterminateSystems/obs-cli-linux}: flakehub_push::cli: Preparing release of DeterminateSystems/obs-cli-linux/2.2.3
Error: 
   0: Status 400 Bad Request from metadata POST
      Invalid URL: unexpected character '.' after patch version number

Location:
   src/cli/mod.rs:514

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: flakehub_push::cli::push_new_release with repository=DeterminateSystems/obs-cli-linux mirror=false upload_name=DeterminateSystems/obs-cli-linux source=/nix/store/0grsb1nqjvnkyyk1qz6jmqz1369xbrax-source
      at src/cli/mod.rs:331
   1: flakehub_push::cli::flakehub_push
      at src/cli/mod.rs:169

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Consider reporting this error using this URL: /issues/new
Error: Process completed with exit code 1.
```

- Action Log: https://github.com/DeterminateSystems/obs-cli-linux/actions/runs/5866709338/job/15906033457

## Expectation

I expect to have the ability to set the `rolling-prefix` with major.minor.patch semver and flakehub_push increment the revision.
