### ISSUE TITLE
Description is not showing for some flakes

### ISSUE THREAD

**Issue by srid** [DeterminateSystems/flakehub-push#66]
2/6 flakes don't have a description (see below).  Take a look at one of them https://github.com/srid/nixci - which has the description  "Define and build CI for Nix projects anywhere".

I had assumed that this action used description of the Github repo. But I just learned that it uses the flake's `description` attribute. Perhaps this should be mentioned in the https://flakehub.com/new page? Another thing worth mentioning is that when adding a github action it won't push existing tags, only tags pushed after the action is added (is that intended behaviour? If so, how would I push existing tags?).

<img width="1258" alt="image" src="https://github.com/DeterminateSystems/flakehub-push/assets/3998/e686a081-f1e8-4f57-a69e-f70560e08c89">

**Comment by lheckemann** [comment]
The description currently comes from your `flake.nix`'s description, not the GitHub repository description.

We may want to fall back to the repository description if none is present, however.

**Comment by grahamc** [comment]
Hi @srid,

Thanks for the issue. Yesterday we updated the documentation and wizard to support pushing existing tags. You can re-run the wizard (though clicking the 'add to github' button won't work...) to get an updated version: https://flakehub.com/new

We'll update the docs & site to talk about where the different bits of data come from. Thanks!

**Comment by grahamc** [comment]
I took a look at your workflow, and you're missing some other important parts as well around the handling of `inputs.tag`:

```yaml
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v3"
        with:
          ref: "${{ (inputs.tag != null) && format('refs/tags/{0}', inputs.tag) || '' }}"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          visibility: "public"
          tag: "${{ inputs.tag }}"
```
